
/*
 * This Java source file was generated by the Gradle 'init' task.
 
package compiler;

public class Compiler {
    public static void main(String[] args) {
        System.out.println("Hello from the compiler !");
    }
}
/* */
package compiler;

import compiler.Lexer.Lexer;
import compiler.Lexer.Symbol;

import java.io.FileReader;
import java.io.IOException;

public class Compiler {

    public static void main(String[] args) {

        if (args.length >= 2 && args[0].equals("-lexer")) {

            try {
                FileReader reader = new FileReader(args[1]);
                Lexer lexer = new Lexer(reader);

                Symbol symbol;

                while (true) {
                    symbol = lexer.getNextSymbol();
                    System.out.println(symbol);
                    /*
                    if (symbol.toString().equals("EOF")) {
                        break;
                    }
                    */
                    if (symbol.getType() == Symbol.TokenType.EOF){
                        break;
                    }
                }

            } catch (IOException e) {
                System.err.println("Error: " + e.getMessage());
                System.exit(1);
            }


        } else {
            System.out.println("Usage: -lexer <filepath>");
        }
    }
}