
/*
 * This Java source file was generated by the Gradle 'init' task.

package compiler;

public class Compiler {
    public static void main(String[] args) {
        System.out.println("Hello from the compiler !");
    }
}
/* */
package compiler;

import compiler.Lexer.Lexer;
import compiler.Lexer.Symbol;
import compiler.parser.AST.ASTNode;
import compiler.parser.AST.ProgramNode;
import compiler.parser.Parser;
import compiler.Semantic_Analysis.Semantic_Analysis;

import java.io.FileReader;
import java.io.IOException;

public class Compiler {

    public static void main(String[] args) {

        if (args.length >= 2 && args[0].equals("-lexer")) {

            try {
                FileReader reader = new FileReader(args[1]);
                Lexer lexer = new Lexer(reader);

                Symbol symbol;

                while (true) {
                    symbol = lexer.getNextSymbol();
                    System.out.println(symbol);
                    /*
                    if (symbol.toString().equals("EOF")) {
                        break;
                    }
                    */
                    if (symbol.getType() == Symbol.TokenType.EOF){
                        break;
                    }
                }

            } catch (IOException e) {
                System.err.println("Error: " + e.getMessage());
                System.exit(1);
            }


        }else if (args.length >= 2 && args[0].equals("-parser")) {
            try {
                FileReader reader = new FileReader(args[1]);
                Lexer lexer = new Lexer(reader);
                Parser parser = new Parser(lexer);

                ASTNode root = parser.getAST();
                System.out.print(root.toString());

            } catch (IOException e) {
                System.err.println("Error: " + e.getMessage());
                System.exit(1);
            }
        }
        else if (args.length >= 2 && args[0].equals("-semantic")) {
            try {
                FileReader reader = new FileReader(args[1]);
                Lexer lexer = new Lexer(reader);
                Parser parser = new Parser(lexer);
                ASTNode root = parser.getAST();

                if (root instanceof ProgramNode program) {
                    Semantic_Analysis analyzer = new Semantic_Analysis();
                    analyzer.analyze(program);
                    System.out.println("OK"); 
                    System.exit(0);
                } else {
                    System.err.println("Error: Root is not a ProgramNode");
                    System.exit(1);
                }
            } catch (IOException e) {
                System.err.println("Error reading file: " + e.getMessage());
                System.exit(1);
            } catch (Semantic_Analysis.SemanticException e) {
                System.err.println(e.getMessage());
                System.exit(2);
            } catch (Exception e) {
                System.err.println("Other Error: " + e.getMessage());
                System.exit(1);
            }
        }
    
        else {
            System.out.println("Usage: -lexer <filepath> | -parser <filepath> | -semantic <filepath>");
        }
    }
}